{
 "title": "mwaa_metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Dags in Last Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select cast(total_dags as integer) as total_dags from \"mwaa_metrics\".\"dags_stats\"  order by time desc LIMIT 1",
     "table": "\"dags_stats\""
    }
   ]
  },
  {
   "title": "Total success dags in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select cast(success_dags as integer) as success_dags from \"mwaa_metrics\".\"dags_stats\"  order by time desc LIMIT 1",
     "table": "\"dags_stats\""
    }
   ]
  },
  {
   "title": "Total failed dags in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select cast(failed_dags as integer) as failed_dags from \"mwaa_metrics\".\"dags_stats\"  order by time desc LIMIT 1",
     "table": "\"dags_stats\""
    }
   ]
  },
  {
   "title": "Total running dags in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select cast(running_dags as integer) as running_dags from \"mwaa_metrics\".\"dags_stats\"  order by time desc LIMIT 1",
     "table": "\"dags_stats\""
    }
   ]
  },
  {
   "title": "Total Dag average duration in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select cast(average_duration as double) as average_duration from \"mwaa_metrics\".\"dags_stats\"  order by time desc LIMIT 1",
     "table": "\"dags_stats\""
    }
   ]
  },
  {
   "title": "Hourly chart for Total, Success and failed dags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawQuery": "select time,\n       cast(total_dags as integer) as total_dags, \n       cast(success_dags as integer) as success_dags, \n       cast(failed_dags as integer) as failed_dags ,\n       cast(running_dags as integer) as running_dags \nfrom \"mwaa_metrics\".\"dags_stats\" "
    }
   ]
  },
  {
   "title": "Average duration of All Dags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select time, cast(average_duration as double) as average_duration from \"mwaa_metrics\".\"dags_stats\" ",
     "table": "\"dags_stats\""
    }
   ]
  },
  {
   "title": "Average duration of successful Dags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select time, cast(average_duration_success as double) as average_duration_success from \"mwaa_metrics\".\"dags_stats\" ",
     "table": "\"dags_stats\""
    }
   ]
  },
  {
   "title": "Average duration of failed Dags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "database": "\"mwaa_metrics\"",
     "measure": "dags_count",
     "rawQuery": "select time, cast(average_duration_failed as double) as average_duration_failed from \"mwaa_metrics\".\"dags_stats\" ",
     "table": "\"dags_stats\""
    }
   ]
  }
 ]
}